### ISSUE TITLE
Issue with non rectangular CQUAD4 

### ISSUE THREAD

**Issue by oriol1993** [vtpasquale/NASTRAN_CoFE#19]
Dear Anthony,

It seems to me that there might be an issue (or limitation) with the stiffness matrix of the cquad4 element. I have tested a case with structured rectangular matrix and results are ok compared to MSC Nastran. However, I have tested more distorted meshes and results become singular. Find attached a simple example.

Thanks for your work,
[Issue_CQUAD4.txt](https://github.com/vtpasquale/NASTRAN_CoFE/files/8148460/Issue_CQUAD4.txt)
.

**Comment by vtpasquale** [comment]
Oriol, thanks for the feedback, and for providing the example case.

Some background information: the CoFE v5 CQUAD4 element is a classical membrane element and a Mindlin plate element superimposed. Reduced integration is used for membrane shear and transverse shear stiffness calculations – this is to avoid shear lock for certain cases. Also, artificial drilling stiffness is added to avoid drilling stiffness singularities – the drilling stiffness approach is similar to commercial Nastran CQUAD4 but not identical. 

There are a lot of tradeoffs involved in formulating a CQUAD4 element; there is no easy way to get a CQUAD4 formulation that works well in a wide variety of situations. When compared to a default commercial Nastran CQUAD4 element, the CoFE CQUAD4 formulation will be more prone to numerical issues as the elements distort and warp. Also, the reduced integration may lead to spurious modes (singularities) for some unusual boundary conditions.

I too observe a singularity for the test case you provided. The case is a disk with a gravity load and with four nodes fixed at 90-degree spacing along the perimeter. The constraint seems a little unusual to me. **I get reasonable results from CoFE when I modify the constraint to fix the entire perimeter of the disk. See the attached example:** 
[oriol1993-fulledgesupport-000.txt](https://github.com/vtpasquale/NASTRAN_CoFE/files/8149097/oriol1993-fulledgesupport-000.txt)

Two questions:

1. Is this boundary condition representative of a case you will be needing to evaluate? 
2. Did you observe that a different (less distorted) mesh had singular results with the same boundary conditions?

**Comment by oriol1993** [comment]
Hi,
Thanks for your response,

1. Yes, my intention is to model an almost flat plate (telescope mirror), supported at some points. Actually, it should be simply supported, but I began with clamped supports to have a more constrained model.
2. No. The other meshes I tested had different type of supports. I have just tested a square supported in each corner and I get equivalent strange results, similar to the example. My assumption of the cause of the problem was wrong.

I see the difficulty, actually it is not critical, results with the ctria3 are completely ok as far as I have tested, but I wanted to have mixed mesh.

Thanks!
Oriol

**Comment by vtpasquale** [comment]
Thanks for sharing, Oriol.

The CQUAD4 singularity is resolved if I extend the 90-degree-spaced constraints from a single node at each location to a single element edge (two nodes) at each location. See the example here:
[oriol_mod3-000.txt](https://github.com/vtpasquale/NASTRAN_CoFE/files/8149399/oriol_mod3-000.txt)
This worked for both simply supported and clamped constraints. You could adjust the mesh as desired to maintain symmetry and keep the supported edges small. That may be preferable to triangles depending on your needs.

**Comment by oriol1993** [comment]
I appreciate your suggestion. Since it is a parametric model and mesh generation, it will be a bit of a mess. Also, I do not want to spuriously constraint the rotations with the pair of constraints. I will stick with the triads for the moment, I just wanted to make sure it was not just a bug.

Thanks for your support :)
